blank_issues_enabled: false
contact_links:
  - name: ❓ Wiki & Documentação
    url: https://github.com/vncsmnl/BigON/wiki/
    about: Consulte os guias e documentação para tirar dúvidas sobre a extensão e análises Big-O.
